#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;
use Importer\Console\Commands\Import\ImportProducts;

$app = new Application();
$app->add(new ImportProducts());
$app->run();
