#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Console\Commands\Import\ImportProducts;

$app = new Application();
$app -> add(new ImportProducts());

try {
    $app->run();
} catch (Exception $e) {
    //
}