<?php namespace App\Console\Commands\Import;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportProducts extends Command
{
    public function configure()
    {
        $this->setName('import:products')
            ->setDescription('Import products from a file and insert them into to the database.')
            ->setHelp('This command allows you to import products from a file to the database. To use: simply run "php console import:product <filename>".')
            ->addArgument('file', InputArgument::REQUIRED, 'The file containing the products.');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}